name: Check NTHU OGA Posts
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Check NTHU OGA posts
        run: |
          # Save output separately to extract notification content
          scrape_output=$(python scripts/check_nthu.py 2>&1)
          
          # Extract only the notification part (everything after "Updates in NTHU OGA Posts")
          notification_content=$(echo "$scrape_output" | sed -n '/Updates in NTHU OGA Posts/,$p')
          
          if [[ -n "$notification_content" ]]; then
            echo "NOTIFICATION_CONTENT<<EOF" >> $GITHUB_ENV
            echo "$notification_content" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Send email
        if: env.NOTIFICATION_CONTENT != ''
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Updates in NTHU OGA Posts
          to: ${{ secrets.EMAIL_USERNAME }}
          from: GitHub Action
          body: ${{ env.NOTIFICATION_CONTENT }}
