name: Check NTHU OGA Posts
on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 8:00 UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  actions: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify exact version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create data directory
        run: mkdir -p data
        
      - name: Run scraper
        run: |
          # Run the script and capture output
          python .github/scripts/check_nthu.py > output.txt 2>&1
          cat output.txt
          
      - name: Check for notification content
        run: |
          # Check if the script identified any updates
          if grep -q "Updates in NTHU OGA Posts" output.txt; then
            # Extract only the notification part
            notification_content=$(grep -A 20 "Updates in NTHU OGA Posts" output.txt)
            
            echo "NOTIFICATION_CONTENT<<EOF" >> $GITHUB_ENV
            echo "$notification_content" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

      - name: Send email
        if: env.NOTIFICATION_CONTENT != ''
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Updates in NTHU OGA
          to: ${{ secrets.EMAIL_USERNAME }}
          from: Github nthu-oga
          body: ${{ env.NOTIFICATION_CONTENT }}
